<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book [

<!ELEMENT book (booking)>
<!ELEMENT booking (name,email,phone,tour)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT tour (#PCDATA)>

]>

<book>
 <booking>
  <name>John Smith</name>
  <email>john@gmail.com</email>
  <phone>9873745789</phone>
  <tour>Charter fishing trip</tour>
</booking>
<booking>
  <name>JohnSmith</name>
  <email>john@gmail.com</email>
  <phone>9873945789</phone>
  <tour>Airboat</tour>
</booking>
</book>
